name: zaginiona
description: "OFFLINE - a found phone text-based puzzle/horror game."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  # Place wallpapers and other static images inside assets/images/.
  # The lock screen wallpaper should be assets/images/lockscreen_wallpaper.jpg.
  # The home screen wallpaper should be assets/images/home_wallpaper.jpg.
  assets:
    - assets/images/
    - assets/images/photos/
    - assets/audio/
