name: zaginiona
description: "OFFLINE - a found phone text-based puzzle/horror game."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  provider: ^6.1.5+1
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5
  audioplayers: ^6.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  in_app_purchase: ^3.2.3
  sentry_flutter: ^9.21.0
  package_info_plus: ^10.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  sentry_dart_plugin: ^3.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  fake_async: ^1.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  generate: true

  # Place wallpapers and other static images inside assets/images/.
  # The lock screen wallpaper should be assets/images/lockscreen_wallpaper.jpg.
  # The home screen wallpaper should be assets/images/home_wallpaper.jpg.
  assets:
    - assets/images/
    - assets/images/photos/
    - assets/audio/
    - assets/l10n/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: grim-origin
